language: rust
sudo: required
rust:
- stable
- beta
- nightly

env:
  - secure: MPJBhwdaWtU4jHojjxjGYuosn9s4C4qKgbcHUouc2Nw1UW6Fk6Qtt27VxAnoB7XyKCnEQRHLyM6/oyDIu0xeRYxnoBms3VltmqYsJJ6htpoG1S9kgjUCagQqIwzTIecQGP0q3tFSa7Ua1wwMmYttkjIMr7kyQj6ifscvyXwmDmlCMRFvYtD8X4SC01F7LQS6BDN83+Y7YPptcztQH521y3DesvS2ps4ZbvGsLEO1Yc9P6pmzyTWZxAMtx8ksRzaWTXgQRljYr2hZwuM3mpEm2fXjdAvhx1NOHfusGbl4q2MGBLGEwn6RKPg6hDpHvAOahv+dHpijIgoKEIy/XpA/rb+lqwE6Ld2pNP7QU/c7+La9TvRPtMIkiootcw6+fSr4Qj5Jvqegc5P+qrdev8OAQ68h3PkJKWjnhEyScR8390OrD24jdRyaBAifxsfXdciLkTpg23PVWc5fUaZUMqe3Eagmtz58SbETbfWxOxD7MQpjn+jO4v4plmWBbOztMzLeJ1FQO6xKn8h9unPboPknOrhgCtEN0vIR0xTW5MDz84WFGMGJ6eKEOEMgX4YCNNH5C6vilpaLbDcvHcZVRJsFD5Jts6/5i9x0Q3nLMWpMaZrrkjfs06IkvxOZ/nt2TPVN4bDrbKK4bkLaRUV9ran58mBUknhBXQUDHVwZuVwcC30=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev
    - libiberty-dev
before_cache: |
  if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  fi

after_success: |
  if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
    cargo doc
    cargo publish --token "$CARGO_API" --allow-dirty
  fi